### ISSUE TITLE
Request: Remove right click context menu on sequencer

### ISSUE THREAD

**Issue by tnmyk** [mxfng/drumhaus#7]
A bit annoying when keeps opening again and again. Happy to create a PR

![image](https://github.com/mxfng/drumhaus/assets/73903781/955a496e-2208-4c3a-972c-8e1045de2b22)

**Comment by mxfng** [comment]
Is this issue frequent using a regular mouse or is it a trackpad?

**Comment by tnmyk** [comment]
Happens with both, mouse and trackpad. 
I was actually trying to use it the same way I use FL studio 😅
